### PR TITLE
Finished Step 3

### PR DESCRIPTION
**Pull request by xu-jiach**
## CHECKS :warning:

Please make sure you are aware of the following.

- [ ] **The changes in this PR doesn't have private information

### CODE REVIEW

**Review by noliver-ykc — APPROVED** [review]
LGTM

**Review by iggyray — APPROVED** [review]
lgtm!
1 small comment is that at line 62, because it always starts with an empty array, I think previous items that were saved on `items.json` may not be carried over to the new array. But the task requirements of the task did not specify us to do that so I think it is looks good nonetheless!

**Comment by xu-jiach** [comment]
> lgtm! 1 small comment is that at line 62, because it always starts with an empty array, I think previous items that were saved on `items.json` may not be carried over to the new array. But the task requirements of the task did not specify us to do that so I think it looks good nonetheless!

**Comment by noliver-ykc** [comment]
> lgtm! 1 small comment is that at line 62, because it always starts with an empty array, I think previous items that were saved on `items.json` may not be carried over to the new array. But the task requirements of the task did not specify us to do that so I think it looks good nonetheless!

I wrote mine the same as Jiachen (except i just created a seperate file, and then initialized it with the same empty array). Any suggestions on how to fix this? When I just left the items.json file blank, it wouldnt populate at all.

**Pull request merged**
